# Generated by Django 4.2.1 on 2023-06-19 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_registro', '0006_persona_ciudad_nacimiento_persona_ciudad_residencia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='comuna_barrio',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='persona',
            name='identidad_etnico_racial',
            field=models.CharField(max_length=150),
        ),
    ]
