# Generated by Django 4.2.1 on 2024-05-06 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profesional',
            fields=[
                ('id_profesional', models.AutoField(primary_key=True, serialize=False)),
                ('nick', models.CharField(max_length=150)),
                ('nombre', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=150)),
            ],
        ),
    ]
