# Generated by Django 4.2.1 on 2024-06-07 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_profesional', '0002_alter_profesional_nick'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profesional',
            old_name='id_profesional',
            new_name='id',
        ),
    ]
