# Generated by Django 4.2.1 on 2024-06-11 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_profesional', '0004_userprofesional'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofesional',
            options={},
        ),
        migrations.AlterModelManagers(
            name='userprofesional',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='userprofesional',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='userprofesional',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='userprofesional',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='userprofesional',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='userprofesional',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='userprofesional',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='userprofesional',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='userprofesional',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='userprofesional',
            name='user_permissions',
        ),
    ]
