# Generated by Django 4.2.1 on 2024-06-11 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_profesional', '0006_alter_userprofesional_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profesional',
            old_name='id',
            new_name='id_profesional',
        ),
        migrations.AlterField(
            model_name='profesional',
            name='nick',
            field=models.CharField(max_length=150),
        ),
    ]
