# Generated by Django 4.2.1 on 2024-06-11 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_profesional', '0007_rename_id_profesional_id_profesional_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofesional',
            name='password',
            field=models.TextField(),
        ),
    ]
