# Generated by Django 4.2.1 on 2024-06-14 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_profesional', '0008_alter_userprofesional_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesional',
            name='first_name',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profesional',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profesional',
            name='last_name',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
    ]
