# Generated by Django 4.2.1 on 2023-06-10 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_registro', '0006_persona_ciudad_nacimiento_persona_ciudad_residencia_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seguimiento',
            fields=[
                ('id_seguimiento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_profesional', models.CharField(max_length=150)),
                ('fecha', models.DateField()),
                ('observacion', models.TextField()),
                ('id_persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos', to='app_registro.persona')),
            ],
            options={
                'db_table': 'Seguimiento',
            },
        ),
    ]
