# Generated by Django 4.2.1 on 2024-05-06 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_profesional', '0001_initial'),
        ('app_seguimiento', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seguimiento',
            name='nombre_profesional',
        ),
        migrations.AddField(
            model_name='seguimiento',
            name='id_profesional',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app_profesional.profesional'),
            preserve_default=False,
        ),
    ]
