# Generated by Django 4.2.1 on 2024-05-28 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_profesional', '0001_initial'),
        ('app_seguimiento', '0002_remove_seguimiento_nombre_profesional_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seguimiento',
            name='id_profesional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_profesional.profesional'),
        ),
    ]
