# Generated by Django 4.2.1 on 2024-06-14 20:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_seguimiento', '0003_alter_seguimiento_id_profesional'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seguimiento',
            name='id_profesional',
        ),
        migrations.AddField(
            model_name='seguimiento',
            name='id_profesional',
            field=models.ManyToManyField(related_name='profesionales', to=settings.AUTH_USER_MODEL),
        ),
    ]
