# Generated by Django 4.2.1 on 2024-06-14 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_seguimiento', '0004_remove_seguimiento_id_profesional_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seguimiento',
            old_name='id_profesional',
            new_name='profesionales',
        ),
    ]
